name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 6.0.0
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: stripe_android
      ios:
        default_package: stripe_ios
      web:
        default_package: stripe_web

dependencies:
  flutter:
    sdk: flutter
  stripe_android:
    git:
      url: https://github.com/stepan-bezhuk-axon/flutter_stripe.git
      ref: fox-dev
      path: packages/stripe_android

  stripe_ios:
    git:
      url: https://github.com/stepan-bezhuk-axon/flutter_stripe.git
      ref: fox-dev
      path: packages/stripe_ios

  stripe_platform_interface: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
